<section>
<h1>Liste des produits</h1>
<a href="<?= $requestUrl ?>/admin/products/addproduct">Ajouter un produit</a>

    <table>
        <thead>
            <th>Id</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Image</th>
            <th>Modif/Suppr</th>
        </thead>
        <tbody>
            <?php foreach($categories as $categorie):?>
                <tr>
                    <td><?=$categorie['idcategories']?></td>
                    <td><?=$categorie['categorie_name']?></td>
                    <td><?=$categorie['categorie_description']?></td>
                    <td><img src="<?= $wwwUrl ?>/images/tea/<?=$categorie['categorie_picture']?>" alt="Tasse de <?=$categorie['categorie_name']?>" /></td>
                    <td><a href="<?= $requestUrl ?>/admin/categories/editcategorie?id=<?=$categorie['idcategories']?>"><i class="fas fa-edit"></i></a> <a href="<?= $requestUrl ?>/admin/categories/delcategorie?id=<?=$categorie['idcategories']?>"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>