<!-- Page d'ajout d'une catégorie -->
<h1>Modifier la catégorie</h1>
<!-- Formulaire de saisie d'un nouvel article -->
<form action="<?= $requestUrl ?>/admin/categories/editcategorie" method="post" enctype="multipart/form-data">

    <fieldset>
        <legend>Informations</legend>
        <p>
            <label for="name">Nom :</label></br>
            <input type="text" id="name" name="name" value="<?=$categorie['categorie_name']?>">
        </p>
        <p>
            <label class="textarea" for="contents">Description :</label></br>
            <textarea id="contents" name="contents" rows="15"><?=$categorie['categorie_description']?></textarea>
        </p>
        <p>
            <label for="picture">Image :</label></br>	
            <input type="file" name="picture" id="picture" accept="image/png,image/jpeg,image/gif">
            <input type="hidden" name="originalpicture" value="<?=$categorie['categorie_picture']?>">
            <input type="hidden" name="id" value="<?=$categorie['idcategories']?>">
        </p>
            <input type="submit" value="Enregistrer" >
    </fieldset>
</form>